repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=5000']
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json|pnpm-lock.yaml

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
    -   id: eslint
        files: \.(js|jsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.45.0
          - eslint-plugin-react@7.32.2
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-react-refresh@0.4.3

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, json, css, markdown]
        exclude: package-lock.json|pnpm-lock.yaml

